code_version: v7.0
group_name: ''
seed: 0

llm:
  path: openai/gpt-4o
  backend: OpenAI
  render: false
  temperature: 0.0
  top_p: 1.0
  iter: 0
  reasoning: null  # on | off | null(=model default). Requires OpenRouter backend.

mix_llm: [] # disable
debug: false

# Ideally we would only need to change the following two lines to run a different experiments
  

defaults:
- _self_
- experiment: basic


hydra:
  run:
    dir: ./outputs/${uuid:}
  searchpath:
    - ./simulation/scenarios/fishing/conf
    - ./simulation/scenarios/sheep/conf
    - ./simulation/scenarios/pollution/conf
